Start IPython manually instead of embedding
Prevents a category of scoping issues which happen as a result of
embedding IPython https://github.com/ipython/ipython/issues/12199

The following example would previously break in `gearbox tgshell` when
running with embedded IPython

In [1] x = 10

In [2]: def foo():
   ...:     return x
   ...:

In [3]: foo()
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 foo()

Input In [2], in foo()
      1 def foo():
----> 2     return x

NameError: name 'x' is not defined